# Generated by Django 5.0.3 on 2024-03-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_adress_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rut',
        ),
    ]
